### ISSUE TITLE
mod_npcweaponvisual

### ISSUE THREAD

**Issue by zaicopx** [MaDmaX1337/AzerothCore-Converted-Modules-to-latest-TrinityCore#1]
I got error when using mod_npcweaponvisual.
`[1264] Out of range value for column 'item_guid' at row 1
Unhandled MySQL errno 1264. Unexpected behaviour possible.`

**Comment by TheFrozenThr0ne** [comment]
Sorry i'm now on [AzerothCore](https://www.azerothcore.org/). I do not give support to it anymore.

But you can compare or try to use the  sql file from this Module: [AzerothCore Weapon Vidual Module](https://github.com/azerothcore/mod-weapon-visual)

Good Luck!
