### ISSUE TITLE
Beastmaster - No Focus Non Hunter Pet 

### ISSUE THREAD

**Issue by Riveir** [MaDmaX1337/AzerothCore-Converted-Modules-to-latest-TrinityCore#2]
The Non Hunter pets don't have any focus bar is there something that can be done to resolve that?

**Comment by TheFrozenThr0ne** [comment]
Sorry i'm now on [AzerothCore](https://www.azerothcore.org/). So i do not give support to this anymore.

But you can compare with this Module: [AzerothCore Beastmaster Module](https://github.com/azerothcore/mod-npc-beastmaster)

Good luck.
